#pragma once

enum Command {
  CMD_SET_LED = 1,
  CMD_STATE_CHANGED = 2,
  CMD_BUTTON_PRESS = 3
};

enum DeviceType {
  DEVICE_SEARCH_POINT = 1,
  DEVICE_SHUTTER = 2,
  DEVICE_DOOR = 3,
  DEVICE_KEY_RACK = 4
};

enum DoorStates {
  DOOR_STATE_CLOSED = 1,
  DOOR_STATE_CLOSING = 2,
  DOOR_STATE_OPEN = 3,
  DOOR_STATE_OPENING = 4,
  DOOR_STATE_ERROR = 5
};
